version: "3.7"

services:
  www:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/nginx/nginx.conf
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: projeto_gazin
      MYSQL_DATABASE: projeto_gazin
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    tty: true
    ports: 
      - "4306:3306"

  backend:
    build: "./backEnd/projeto"
    image: my-laravel-image
    container_name: laravel
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - db

  frontend:
    build: ./frontEnd/app
    image: vue-ui
    container_name: vue-ui
    restart: always
    volumes:
      - ./frontEnd/app:/home/node/app
    tty: true
    ports:
      - "80:80"
    depends_on:
      - backend



  
      
