version: "3.7"

networks:
  bridge:

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: projeto_gazin
      MYSQL_DATABASE: projeto_gazin
      MYSQL_USER: root
      MYSQL_PASSWORD: projeto_gazin
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    networks: 
      - bridge
  backend:
    build: "./backEnd/projeto"
    image: my-laravel-image
    container_name: laravel
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - db
    networks: 
      - bridge

  frontend:
    build: ./frontEnd/app
    container_name: Vueui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on: 
      - db
    ports: 
      - "8081:80"
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: projeto_gazin
    networks: 
      - bridge



  
      
